# Form implementation generated from reading ui file 'add_film.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.name_input = QtWidgets.QLineEdit(parent=Form)
        self.name_input.setObjectName("name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name_input)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.genre_input = QtWidgets.QLineEdit(parent=Form)
        self.genre_input.setObjectName("genre_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.genre_input)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.year_input = QtWidgets.QLineEdit(parent=Form)
        self.year_input.setObjectName("year_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.year_input)
        self.is_watched = QtWidgets.QRadioButton(parent=Form)
        self.is_watched.setObjectName("is_watched")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.is_watched)
        self.save_button = QtWidgets.QPushButton(parent=Form)
        self.save_button.setObjectName("save_button")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.save_button)
        self.notes_input = QtWidgets.QTextEdit(parent=Form)
        self.notes_input.setObjectName("notes_input")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.notes_input)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.image_input = QtWidgets.QLineEdit(parent=Form)
        self.image_input.setObjectName("image_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.image_input)
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.image_button = QtWidgets.QPushButton(parent=Form)
        self.image_button.setObjectName("image_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.image_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Название"))
        self.label_2.setText(_translate("Form", "Жанр"))
        self.label_3.setText(_translate("Form", "Год"))
        self.is_watched.setText(_translate("Form", "Просмотрено"))
        self.save_button.setText(_translate("Form", "Сохранить"))
        self.label_4.setText(_translate("Form", "Заметки"))
        self.label_5.setText(_translate("Form", "Изображение"))
        self.image_button.setText(_translate("Form", "Выбрать изображение"))
